# #### workflow to deploy the landing page to S3 bucket and invalidate cloudfront distribution
name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - dev
      - feature/contact-me

env:
  S3_BUCKET: ecotrack-landing-page
#   CLOUDFRONT_DISTRIBUTION_ID: E3QZ9EXAMPLE

jobs:
  deploy:   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   # you can change this if your project needs another version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync S3 bucket
        run: |
          aws s3 sync ./build s3://$S3_BUCKET --delete
        env:
          S3_BUCKET: ${{ env.S3_BUCKET }}

    #   - name: Invalidate CloudFront distribution
    #     run: |
    #       aws cloudfront create-invalidation \
    #         --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
    #         --paths "/*"
    #     env:
    #       CLOUDFRONT_DISTRIBUTION_ID: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}
            